const mongoose = require('mongoose');

const unitMaintenanceFeeSchema = new mongoose.Schema({
  unit: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Unit',
    required: [true, 'Unit reference is required']
  },
  billingPeriod: {
    month: {
      type: Number,
      required: [true, 'Billing month is required'],
      min: [1, 'Month must be between 1 and 12'],
      max: [12, 'Month must be between 1 and 12']
    },
    year: {
      type: Number,
      required: [true, 'Billing year is required'],
      min: [2020, 'Year cannot be before 2020'],
      max: [2050, 'Year cannot be after 2050']
    }
  },
  feeBreakdown: {
    baseFee: {
      surfaceArea: {
        type: Number,
        required: true,
        min: 0
      },
      ratePerSqFt: {
        type: Number,
        required: true,
        min: 0
      },
      amount: {
        type: Number,
        required: true,
        min: 0
      }
    },
    specialCategories: [{
      category: {
        type: String,
        enum: [
          'additional_parking', 
          'balcony_premium', 
          'pool_access', 
          'gym_access', 
          'storage_unit',
          'garden_access',
          'rooftop_access',
          'concierge_service'
        ],
        required: true
      },
      quantity: {
        type: Number,
        required: true,
        min: 1
      },
      unitFee: {
        type: Number,
        required: true,
        min: 0
      },
      totalFee: {
        type: Number,
        required: true,
        min: 0
      },
      description: {
        type: String,
        trim: true
      }
    }],
    adjustments: [{
      type: {
        type: String,
        enum: ['discount', 'penalty', 'credit', 'additional_charge', 'late_fee', 'waiver'],
        required: true
      },
      description: {
        type: String,
        required: [true, 'Adjustment description is required'],
        trim: true,
        maxlength: [200, 'Description cannot exceed 200 characters']
      },
      amount: {
        type: Number,
        required: true
      },
      appliedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
      },
      appliedDate: {
        type: Date,
        default: Date.now
      },
      reason: {
        type: String,
        trim: true,
        maxlength: [500, 'Reason cannot exceed 500 characters']
      }
    }]
  },
  totalAmount: {
    type: Number,
    required: [true, 'Total amount is required'],
    min: [0, 'Total amount cannot be negative']
  },
  dueDate: {
    type: Date,
    required: [true, 'Due date is required']
  },
  status: {
    type: String,
    enum: ['pending', 'paid', 'overdue', 'partially_paid', 'waived', 'cancelled'],
    default: 'pending',
    required: true
  },
  paymentDetails: {
    paidAmount: {
      type: Number,
      default: 0,
      min: 0
    },
    remainingAmount: {
      type: Number,
      default: function() {
        return this.totalAmount;
      }
    },
    payments: [{
      amount: {
        type: Number,
        required: true,
        min: 0.01
      },
      paidDate: {
        type: Date,
        required: true
      },
      paymentMethod: {
        type: String,
        enum: ['cash', 'bank_transfer', 'check', 'card', 'online', 'other'],
        required: true
      },
      referenceNumber: {
        type: String,
        trim: true,
        maxlength: [50, 'Reference number cannot exceed 50 characters']
      },
      paidBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
      },
      receivedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
      },
      notes: {
        type: String,
        trim: true,
        maxlength: [500, 'Payment notes cannot exceed 500 characters']
      }
    }]
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Generated by user is required']
  },
  generatedDate: {
    type: Date,
    default: Date.now
  },
  lastModifiedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  notifications: {
    remindersSent: {
      type: Number,
      default: 0
    },
    lastReminderDate: {
      type: Date
    },
    overdueNoticeSent: {
      type: Boolean,
      default: false
    }
  },
  linkedTransaction: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Transaction'
  },
  notes: {
    type: String,
    trim: true,
    maxlength: [1000, 'Notes cannot exceed 1000 characters']
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Compound index to ensure unique billing period per unit
unitMaintenanceFeeSchema.index({ 
  unit: 1, 
  'billingPeriod.month': 1, 
  'billingPeriod.year': 1 
}, { unique: true });

// Other indexes for performance
unitMaintenanceFeeSchema.index({ status: 1 });
unitMaintenanceFeeSchema.index({ dueDate: 1 });
unitMaintenanceFeeSchema.index({ generatedBy: 1 });
unitMaintenanceFeeSchema.index({ createdAt: -1 });
unitMaintenanceFeeSchema.index({ 'billingPeriod.year': 1, 'billingPeriod.month': 1 });

// Virtual for checking if fee is overdue
unitMaintenanceFeeSchema.virtual('isOverdue').get(function() {
  return this.dueDate < new Date() && ['pending', 'partially_paid'].includes(this.status);
});

// Virtual for days overdue
unitMaintenanceFeeSchema.virtual('daysOverdue').get(function() {
  if (!this.isOverdue) return 0;
  const today = new Date();
  const diffTime = today - this.dueDate;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
});

// Virtual for billing period display
unitMaintenanceFeeSchema.virtual('billingPeriodDisplay').get(function() {
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  return `${months[this.billingPeriod.month - 1]} ${this.billingPeriod.year}`;
});

// Pre-save middleware to calculate remaining amount
unitMaintenanceFeeSchema.pre('save', function(next) {
  try {
    // Initialize paymentDetails if not exists
    if (!this.paymentDetails) {
      this.paymentDetails = {
        paidAmount: 0,
        remainingAmount: this.totalAmount,
        payments: []
      };
    }

    // Initialize payments array if not exists
    if (!this.paymentDetails.payments) {
      this.paymentDetails.payments = [];
    }

    // Calculate paid amount from payments - with safety check
    if (Array.isArray(this.paymentDetails.payments)) {
      this.paymentDetails.paidAmount = this.paymentDetails.payments.reduce((total, payment) => {
        return total + (payment.amount || 0);
      }, 0);
    } else {
      this.paymentDetails.paidAmount = 0;
    }

    this.paymentDetails.remainingAmount = this.totalAmount - this.paymentDetails.paidAmount;

    // Update status based on payment
    if (this.paymentDetails.paidAmount >= this.totalAmount) {
      this.status = 'paid';
    } else if (this.paymentDetails.paidAmount > 0) {
      this.status = 'partially_paid';
    } else if (this.dueDate < new Date() && this.status === 'pending') {
      this.status = 'overdue';
    }

    next();
  } catch (error) {
    console.error('Pre-save middleware error:', error);
    next(error);
  }
});

// Method to add payment
unitMaintenanceFeeSchema.methods.addPayment = function(paymentData) {
  if (!this.paymentDetails) {
    this.paymentDetails = { payments: [] };
  }
  
  if (!this.paymentDetails.payments) {
    this.paymentDetails.payments = [];
  }
  
  this.paymentDetails.payments.push(paymentData);
  return this.save();
};

// Method to add adjustment
unitMaintenanceFeeSchema.methods.addAdjustment = function(adjustmentData) {
  if (!this.feeBreakdown.adjustments) {
    this.feeBreakdown.adjustments = [];
  }

  this.feeBreakdown.adjustments.push(adjustmentData);

  // Recalculate total amount
  const adjustmentTotal = this.feeBreakdown.adjustments.reduce((total, adj) => {
    return total + adj.amount;
  }, 0);

  const specialCategoriesTotal = (this.feeBreakdown.specialCategories || []).reduce((total, cat) => {
    return total + cat.totalFee;
  }, 0);

  const baseTotal = this.feeBreakdown.baseFee.amount + specialCategoriesTotal;

  this.totalAmount = baseTotal + adjustmentTotal;

  return this.save();
};

// Static method to get overdue fees
unitMaintenanceFeeSchema.statics.getOverdueFees = function() {
  return this.find({
    status: 'overdue'
  }).populate('unit', 'unitNumber floor owner')
    .populate('unit.owner', 'firstName lastName email');
};

// Static method to get fees for specific period
unitMaintenanceFeeSchema.statics.getFeesForPeriod = function(month, year) {
  return this.find({
    'billingPeriod.month': month,
    'billingPeriod.year': year
  }).populate('unit', 'unitNumber floor surfaceArea owner')
    .populate('unit.owner', 'firstName lastName email');
};

// Static method to get unit's fee history
unitMaintenanceFeeSchema.statics.getUnitFeeHistory = function(unitId, limit = 12) {
  return this.find({ unit: unitId })
    .sort({ 'billingPeriod.year': -1, 'billingPeriod.month': -1 })
    .limit(limit)
    .populate('generatedBy lastModifiedBy', 'firstName lastName');
};

module.exports = mongoose.model('UnitMaintenanceFee', unitMaintenanceFeeSchema);
